<?php
$pageTitle='Detalle de pedido web | ERP';require_once __DIR__.'/../includes/db.php';require_once __DIR__.'/../includes/auth.php';requiereModulo('ecommerce');require_once __DIR__.'/../includes/helpers.php';
$service=new \Lteco\Application\Ecommerce\PedidoPanelService(new \Lteco\Infrastructure\Db\Connection($pdo));$id=(int)($_GET['id']??$_POST['id']??0);$idUsuario=(int)(usuarioActual()['IdUsuario']??0);$error='';$ok=(string)($_GET['ok']??'');
if($_SERVER['REQUEST_METHOD']==='POST'){try{requirePost();verifyCsrfOrFail();$accion=(string)($_POST['accion']??'');if($accion==='confirmar_efectivo')$service->confirmarPagoEfectivo($id,$idUsuario);elseif($accion==='reembolso')$service->solicitarReembolso($id,$idUsuario,(string)($_POST['motivo']??''));elseif($accion==='reintentar_correo')$service->reintentarNotificacion($id,(int)($_POST['id_notificacion']??0),$idUsuario);else $service->actualizarEstado($id,(string)($_POST['estado']??''),$idUsuario,(string)($_POST['receptor']??''),(string)($_POST['evidencia']??''));header('Location: ver.php?id='.$id.'&ok=1');exit;}catch(Throwable$e){$error=$e->getMessage();$service->registrarErrorOperativo($id,$idUsuario,(string)($_POST['accion']??'desconocida'),$error);}}
try{$d=$service->detalle($id);}catch(Throwable$e){http_response_code(404);exit(h($e->getMessage(),''));}$p=$d['pedido'];
require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/sidebar.php';
function pedidoFecha(mixed $v):string{return $v?date('d/m/Y H:i',strtotime((string)$v)):'—';}
?>
<main class="main"><div class="topbar"><div><a href="index.php">← Pedidos web</a><h1><?=h($p['NumeroPedido'],'')?></h1><p class="subtle">Ficha operativa, cobro, entrega y trazabilidad.</p></div></div>
<?php if($ok):?><div class="notice notice--success">Pedido actualizado correctamente.</div><?php endif?><?php if($error):?><div class="notice notice--error"><?=h($error,'')?></div><?php endif?>
<div class="cards"><div class="card"><small>Estado</small><strong><?=h($p['Estado'],'')?></strong></div><div class="card"><small>Pago</small><strong><?=h($p['EstadoPago'].' · '.$p['ProveedorPago'],'')?></strong></div><div class="card"><small>Total</small><strong><?=h($p['Moneda'].' '.number_format((float)$p['Total'],2,',','.'),'')?></strong></div><div class="card"><small>Reserva hasta</small><strong><?=h(pedidoFecha($p['ExpiraEn']),'')?></strong></div></div>
<div class="cards"><section class="card"><h2>Cliente y facturación</h2><p><strong><?=h(trim($p['Nombre'].' '.$p['Apellido']),'')?></strong><br><?=h($p['Correo'],'')?><br><?=h($p['Telefono'],'')?><br>Cédula: <?=h($p['Cedula']?:'No informada','')?></p><p><?=h($p['Direccion'],'')?><?php if($p['CodigoPostal']):?> · CP <?=h($p['CodigoPostal'],'')?><?php endif?><br><?=h($p['Ciudad'].', '.$p['Departamento'],'')?></p></section><section class="card"><h2>Gestión</h2>
<?php if($p['ProveedorPago']==='cash'&&$p['Estado']==='PagoEnRevision'):?><p><strong>Confirmá únicamente después de recibir el total.</strong> Esta acción crea la venta y consume las unidades reservadas.</p><form method="post" onsubmit="return confirm('¿Confirmás que recibiste el total en efectivo?');"><?=csrfInput()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="accion" value="confirmar_efectivo"><button class="btn-primary">Confirmar efectivo</button></form><?php endif?>
<?php $next=['Pagado'=>['Preparando'],'Preparando'=>['Listo'],'Listo'=>['Entregado'],'PendientePago'=>['Cancelado'],'PagoEnRevision'=>['Cancelado']][$p['Estado']]??[];if($next):?><form method="post" class="shop-form"><?=csrfInput()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="accion" value="estado"><select name="estado"><?php foreach($next as$n):?><option value="<?=$n?>"><?=$n?></option><?php endforeach?></select><?php if(in_array('Entregado',$next,true)):?><input name="receptor" required placeholder="Nombre de quien recibe"><input name="evidencia" placeholder="Referencia o evidencia"><?php endif?><button class="btn-secondary">Actualizar estado</button></form><?php endif?>
<?php if($p['EstadoPago']==='Aprobado'&&in_array($p['Estado'],['Pagado','Preparando','Listo'],true)):?><form method="post" class="shop-form"><?=csrfInput()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="accion" value="reembolso"><input name="motivo" required placeholder="Motivo del reembolso"><button class="btn-secondary">Iniciar reembolso</button></form><?php endif?></section></div>
<h2>Unidades</h2><div class="table-wrap"><table class="table"><thead><tr><th>Unidad</th><th>Modelo</th><th>Batería / color</th><th>Número de motor</th><th>Total</th></tr></thead><tbody><?php foreach($d['items'] as$i):?><tr><td><?=h($i['IdVehiculo'],'')?></td><td><?=h($i['Modelo'],'')?></td><td><?=h(($i['CapacidadBateriaAh']?$i['CapacidadBateriaAh'].'Ah · ':'').$i['Color'],'')?></td><td><?=h($i['NumeroMotor']?:'—','')?></td><td><?=h($p['Moneda'].' '.number_format((float)$i['Total'],2,',','.'),'')?></td></tr><?php endforeach?></tbody></table></div>
<h2>Pagos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Proveedor</th><th>Tipo</th><th>Estado</th><th>Monto</th><th>Referencia</th></tr></thead><tbody><?php if(!$d['pagos']):?><tr><td colspan="6">Todavía no hay movimientos de pago.</td></tr><?php endif?><?php foreach($d['pagos'] as$x):?><tr><td><?=h(pedidoFecha($x['CreadoEn']??null),'')?></td><td><?=h($x['Proveedor'],'')?></td><td><?=h($x['Tipo'],'')?></td><td><?=h($x['Estado'],'')?></td><td><?=h($x['Moneda'].' '.number_format((float)$x['Monto'],2,',','.'),'')?></td><td><?=h($x['IdExterno']??'','')?></td></tr><?php endforeach?></tbody></table></div>
<h2>Correos transaccionales</h2><div class="table-wrap"><table class="table"><thead><tr><th>Tipo</th><th>Destino</th><th>Estado</th><th>Intentos</th><th>Último resultado</th><th></th></tr></thead><tbody><?php if(!$d['notificaciones']):?><tr><td colspan="6">No hay correos asociados.</td></tr><?php endif?><?php foreach($d['notificaciones'] as$n):?><tr><td><?=h($n['Tipo'],'')?></td><td><?=h($n['Destinatario'],'')?></td><td><?=h($n['Estado'],'')?></td><td><?=(int)$n['Intentos']?></td><td><?=h($n['UltimoError']?:pedidoFecha($n['EnviadaEn']??null),'')?></td><td><?php if($n['Estado']==='Fallida'):?><form method="post"><?=csrfInput()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="accion" value="reintentar_correo"><input type="hidden" name="id_notificacion" value="<?=(int)$n['IdNotificacion']?>"><button class="btn-secondary btn-small">Reintentar</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div>
<h2>Historial y auditoría</h2><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Acción</th><th>Cambio</th><th>Usuario</th><th>Detalle</th></tr></thead><tbody><?php foreach($d['auditoria'] as$a):?><tr><td><?=h(pedidoFecha($a['CreadoEn']),'')?></td><td><?=h($a['Accion'],'')?></td><td><?=h(($a['EstadoAnterior']?:'—').' → '.($a['EstadoNuevo']?:'—'),'')?></td><td><?=h($a['UsuarioNombre']?:'Sistema','')?></td><td><small><?=h($a['MetadataJson']??'','')?></small></td></tr><?php endforeach?></tbody></table></div></main><?php require __DIR__.'/../includes/footer.php';?>
